### ISSUE TITLE
Menubar icon not showing up in Yosemite Dark Mode

### ISSUE THREAD

**Issue by coffeesam** [webuildsg/osx#12]
The menubar icon is only visible when I click it and isn't when it is not being clicked.

OS: Yosemite OS X 10.10.3
Options: Dark Mode

It is visible without the Dark Mode option set in OS X's General system preferences.
![screen shot 2015-05-31 at 10 23 01 pm](https://cloud.githubusercontent.com/assets/297375/7902204/a9b26616-07e3-11e5-9f7c-9fa0310f0d71.png)

**Comment by sayanee** [comment]
:+1:

**Comment by cheeaun** [comment]
Relevant to https://github.com/atom/electron/issues/1271

**Comment by sayanee** [comment]
how it looks now:

![image](https://cloud.githubusercontent.com/assets/413879/7904968/8b1d98ac-0841-11e5-8393-d111727a4cf5.png)

**Comment by sayanee** [comment]
@coffeesam please download the [latest release v1.0.1](https://github.com/webuildsg/osx/releases/tag/v1.0.1) all thanks to @cheeaun :tada:

**Comment by cheeaun** [comment]
:+1:
