### ISSUE TITLE
The menubar icon does not hint when webuild.sg feed is updated

### ISSUE THREAD

**Issue by coffeesam** [webuildsg/osx#13]
The menubar icon should change from the black/white version to a colored one to hint the users that the feed is updated.

**Comment by sayanee** [comment]
:+1:

**Comment by cheeaun** [comment]
Relevant to https://github.com/maxogden/menubar/issues/2

**Comment by sayanee** [comment]
closed with #19

**Comment by sayanee** [comment]
thanks @coffeesam @cheeaun @uzyn ✨you can now download all these changes in the [latest release](https://github.com/webuildsg/osx/releases/tag/v1.1.0) :tada:
